# Generated by Django 5.1 on 2025-11-10 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Biblia', '0002_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_venta_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal_detalle', models.DecimalField(decimal_places=2, max_digits=10)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('impuesto_detalle', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notas_item', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_linea', models.PositiveIntegerField()),
                ('producto_id', models.IntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app_Biblia.pedido')),
            ],
            options={
                'verbose_name_plural': 'Detalles de Pedido',
                'ordering': ['pedido', 'numero_linea'],
            },
        ),
    ]
